[package]
name = "leetcode"
version = "0.0.3"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

# leetcode上的题，即便复杂如graph，入参也不过是二维数组，用不到lazy_static去初始化non-primitibe type
# [dependencies]
# lazy_static = "*"