[package]
name = "rust_leetcode"
version = "0.0.1"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [] # 数组为空表示没有别的feature依赖
#unused = []

[dependencies]
#serde = { version = "*", features = ["derive"] }
